### ISSUE TITLE
'.less' files in css folder.

### ISSUE THREAD

**Issue by adsingh14** [beedevservices/beedev-helper#3]
# Expected Behavior
Should I install `.less` package for **css** files or make changes in `.css` files ?

Please describe the behavior you are expecting

# Current Behavior
There's are `.less` files under **css** folder which has not mentioned in `contribution` file. 
What is the current behavior?

**Comment by melissa-24** [comment]
I forgot about adding that to the contribution file.  Sorry about that.  If you install Easy Less extention to vs code you can make changes to the .less file and it will auto update the .css.  IF you are unfamiliar with LESS feel free to make the changes to the .css and I can translate it over

**Comment by melissa-24** [comment]
Just updated the contrubution file  with notes regarding this
